helpers/arguments.py, sdxl-env.sh.example, train_dreambooth.py, train_sdxl.py, train_sdxl.sh
This is done using a workaround that makes sure we never divide by zero.
This will likely be revisited.
=> Min-SNR: using the minimum SNR as an MSE weighted loss

helpers/multiaspect/dataset.py, helpers/multiaspect/sampler.py, train_sd21.py, train_sdxl.py
Additionally, attempt a more cleaner fix by returning False.
=> Add an internal epoch step count so that we can move onto the next epoch

helpers/caching/vae.py, helpers/multiaspect/image.py, train_sdxl.py
Images are only resized when the latents are cached, so, we still have access to the original.
We'll use the original image dimensions and the latent dimensions in combination with the VAE's scaling factor of 8, to mark those correctly.
Previously, the target and original size were identical. We were losing this information and setting the original size to the target.
Now, we'll correctly set it.
=> SDXL: Support for target/original size when resizing images

helpers/multiaspect/sampler.py
In v0.6.0, something seems to have broken where we do not find a valid bucket sometimes.
This resolves that condition, instead ensuring that we have a random selection out of the available range.
=> Random bucket sampling fix

helpers/caching/sdxl_embeds.py, helpers/data_backend/factory.py, helpers/training/state_tracker.py
such that only unprocessed items are managed on each iteration, or, do nothing if already cached in entirety
=> text embedding cache: optimise the generation of embeds 

helpers/caching/sdxl_embeds.py, helpers/legacy/validation.py
Fixes #273 by:
* Using the common `compute_embeddings_for_prompts` instead of the private methods `comptue_embeddings_for_sdxl_prompts`, as those do not do the same level of error checking
* Added logic to the caching mechanism that detects errors in the cache load, to then encode the prompt. It's possible we want to do this only when we're still preparing the training run, since running the text encoder during training will be slow.
=> (#273) add a check for cache load failure during validations preparation

Dockerfile, docker-start.sh
This should make it easier for people to deploy on Runpod, Vast, etc.
Build command:
```
docker buildx build --build-arg "WANDB_TOKEN=" --build-arg "HUGGING_FACE_HUB_TOKEN=" --platform linux/amd64 --output type=docker --provenance false -t bghira/simpletuner:latest .
```
Push command:
```
docker push bghira/simpletuner:latest
```
=> Add Dockerfile

helpers/image_manipulation/brightness.py
Enforces the image being in 8-bit RGB mode for calculate_luminance.
=> Convert image to accepted format for calculate_luminance

helpers/sd3/expanded.py
- Adds the ability to use a larger SD3 with qk norm added back (as LayerNorm)
- Executing the module allows you to convert an existing SD3 module to the expanded module
=> Add SD3 model extension code

helpers/image_manipulation/training_sample.py
Resolves a condition where a mostly-square-image dataset of 1 million images was reduced by half, only ~500k samples were visible.
=> bugfix: capture more samples when their intermediary size is smaller than target.

INSTALL.md, helpers/data_backend/aws.py, helpers/data_backend/local.py, helpers/image_manipulation/load.py, helpers/metadata/backends/json.py
cv2 is faster and more tolerant of corruption than PIL. Also adds a fallback for transparent images that adds a white background, instead of the default which is usually black and looks bad.
I only ran the unit tests, which passed.
=> Load images preferentially with CV2, fall back to PIL only if that fails

helpers/sd3/pipeline.py
I managed to fix the random errors in #546 for myself at least. Debug prints revealed that C<timestep> was randomly either on the CPU or on the GPU. However, after moving C<timesteps> to the GPU, another error happened because C<latents> was also on the CPU. So then I moved C<latents> also to the GPU and the errors were gone.
=> sd3: Fix random errors when generating validation images. (#546)

train_sdxl.py
SD3 text encoder unloading was fixed in commit 7c749772e54434eec3403412b3d1d4e31288fa23 to address issue #457. However, the amount of the freed memory is reported as 0.0 GB because the fix was applied just before the actual training starts.
```
2024-07-07 10:52:57,669 [INFO] (__main__) Unloading text encoders, as they are not being trained.
2024-07-07 10:52:57,753 [INFO] (__main__) After nuking text encoders from orbit, we freed 0.0 GB of VRAM. The real memories were the friends we trained a model on along the way.
```
After moving the code around the amount of memory freed is reported correctly:
```
2024-07-07 11:00:03,781 [INFO] (__main__) Unloading text encoders, as they are not being trained.
2024-07-07 11:00:04,063 [INFO] (__main__) After nuking text encoders from orbit, we freed …
```
=> Fix text encoder unload reporting

helpers/caching/sdxl_embeds.py, helpers/data_backend/aws.py, helpers/data_backend/local.py
Loading of cached text embeds from local disk was broken by commit 20bcf68a215c16d5c6cdd084882f079b7cddcaab. When `cache_dir` is a relative path in multidatabackend.json, the cached text embeds always get regenerated.
Here's an example multidatabackend.json that suffers from this problem:
```
[
{
"id": "pseudo-camera-10k-sd3",
"type": "local",
"crop": false,
"crop_aspect": "square",
"crop_style": "random",
"resolution": 1.0,
"minimum_image_size": 0.25,
"maximum_image_size": 1.0,
"target_downsample_size": 1.0,
"resolution_type": "area",
"cache_dir_vae": "cache/vae/sd3/pseudo-camera-10k",
"instance_data_dir": "/home/mikaelh/Stable Diffusion/datasets/ptx0/pseudo-camera-10k/train",
"disabled": false,
"skip_file_discovery": "",
"caption_strategy": "filename",
"metadata_backend": "json"
},
{ …
```
=> Fix cached text embeds not getting loaded from the disk with local backend and relative path in cache_dir

OPTIONS.md, README.md, documentation/QUICKSTART.md, documentation/quickstart/AURAFLOW.md, helpers/arguments.py, helpers/aura_diffusion/pipeline.py, helpers/caching/sdxl_embeds.py, helpers/data_backend/aws.py, helpers/data_backend/local.py, helpers/legacy/validation.py, helpers/sdxl/save_hooks.py, helpers/training/collate.py, helpers/training/state_tracker.py, helpers/training/validation.py, sdxl-env.sh.example, train_sdxl.py, train_sdxl.sh
This issue encompasses the plan to support Aura Diffusion.
If you wish to take one of the components, simply comment here and open a pull request to this branch (`feature/aura-diffusion`). Please do not open your pull request to the main branch.
- this occurs in multiple places. look for `pixart_sigma` to get an idea of where these occur.
- leave things like text embed cache broken, until they are properly implemented - so that a ValueError etc is raised when something still needs to be "plugged in".
- we have to then `StateTracker.set_model_type("aura_diffusion")`
- this applies when `--aura_diffusion` argument is provided
- a `AURA_DIFFUSION=false` variable export should be added to `sdxl-env.sh.example`
- `train_sdxl.sh` should be updated to address this variable by setting …
=> implement Aura Diffusion training

train.py
PyTorch is really stubborn and doesn't actually nuke the text encoders even if we delete them and set them to none.
Sending them to the "meta" device makes sure that they are nuked.
=> Nuke the text encoders by sending them to "meta"

helpers/data_backend/factory.py
Thanks for supporting jsonl, btw jsonl file crashes here.
Followed similar pattern in `parquet.py`.
=> Fix crash when using jsonl files

helpers/models/flux/pipeline.py
Flux had random validation errors similar to SD3 in issue #546. This pull request makes sure all tensors are moved to the GPU before calling the transformer. Code is mostly copied from helpers/sd3/pipeline.py. In the case of Flux, the transformer also takes in `txt_ids` and `img_ids` parameters which also needed to be moved to GPU.
I did some testing with extra debug prints and the validation image was successfully generated even when tensors were originally on the CPU.
=> Flux: Fix random validation errors due to some tensors being on the cpu

train.py
This pull request improves the configuration support for transformers when using the accelerate library. The changes address issues with incomplete consideration of the transformer's config in the original implementation.
Changes made:
- Modified `train.py` to enhance config support.
Please review the changes and let me know if there are any issues or further modifications needed.
=> Improve config support for transformers with accelerate

config/config.env.example, documentation/quickstart/FLUX.md, helpers/arguments.py, helpers/training/__init__.py, train.py
this is kind of an experimental change.
i was investigating how to fix the LoRA loading issue when we try and resume a checkpoint, as that is currently broken upstream in Quanto.
however, i also discovered that if we send the model to its target dtype before quantising it, the weight is reduced and we can train in even less memory.
this requires the adam_bf16 optimiser be used, so the error messages are updated to reflect that.
you can still use adafactor and others, but it's noted as a bit heavier and requires fp32 base default dtype.
=> quanto: allow further vram reduction with bf16 base weights, reorder model loading operations to evacuate text encoders before DiT loads

train.py
`from diffusers import ChatGLMTokenizer` and `from diffusers import ChatGLMModel`report importError, so I update this codes. and `text_encoder_path = "kwai-kolors/kolors-diffusers"` just only download from the huggingface but can't not load the local path,so I set this code to `text_encoder_path = args.pretrained_model_name_or_path`
=> update something about kolor in the train.py

train.py
Get rid of FluxPipeline inside TextEmbeddingCache that is keeping text encoders in system RAM. This frees up RAM for other things like quantization. Peak RAM usage during fp8 quantization is about 45.4 GB after this change.
=> Flux: Purge text encoders from system RAM.

Dockerfile, docker-start.sh
Moves loading of ENVs to docker start so they can't be baked into the image and accidentally leaked on public registries.
----
@bghira Since this repo is getting more traction, and people seem to be using Docker, I highly recommend we create a CD pipeline to build and deploy the latest tag to a registry. If you're on board, I'll create it in a way where I don't have any access over any part of the process.
Then, we can offer one-click deployment to the major cloud hosts. Manually building the image can get annoying. On my (slow) internet connection, it takes around 3 hours to pull, build and push it (assuming no cache).
----
And the final step would be to build a small web app so that users can interact with SImpleTuner via a UI instead of SSH'ing into the container. I know you've been …
=> Make Docker foolproof

helpers/training/adapter.py, helpers/training/diffusion_model.py, helpers/training/error_handling.py, helpers/training/schedulers.py, helpers/training/text_encoding.py, train.py
This is the first part and aims to improve the readability of `train.py` by:
* Separating chore LoCs into respective modules so that users can focus on more core things. 
* Since the chore LoCs now have their own modules, they should now be fairly extensible i.e., a new error check.  
With this approach, we are able to reduce about 421 LoC to the main entrypoint of SimpleTuner.
=> refactor train.py to reduce LoCs.

OPTIONS.md, helpers/arguments.py, train.py
Input perturbation is a simple trick to speed up training convergence. We just add a little bit of extra noise to the inputs fed to the model.
Input perturbation has already been added to diffusers before:
https://github.com/huggingface/diffusers/issues/3293
Kohya calls this --ip_noise_gamma:
https://github.com/kohya-ss/sd-scripts/pull/798
The original research paper is here:
https://arxiv.org/pdf/2301.11706
I tested input perturbation with Flux LoRA training and it seems to work quite well. I did a little test run at 512px resolution and adamw_bf16 optimizer with 4e-4 learning rate.
500 steps without input perturbation:
500 steps with input perturbation set to 0.1:
I'd say the latter image is already starting look almost fully converged at just 500 steps.
Also, there seems to be less …
=> Add input perturbation

train.py
Fix a mistake in my previous pull request #723. Below is a comparison with 'Before' column having input perturbation at 0.1 all the time and 'After' column having working linear decay. I'm still running main branch code from Sunday (commit 166d905a4506241ab9bb663f96df0bb2d49bdd3d) for these comparisons. There is a clear difference between 'Before' and 'After' but it's hard to tell which is actually better. 'Before' seems to maintain the same pose more consistently.
| Steps | Before (constant input perturbation) | After (linear decay fixed) |
| --- | --- | --- |
| 500 | ![step_500_validation_(512, 512)](https://github.com/user-attachments/assets/49977ecf-df71-4b38-8f65-6c82f3362721) | ![step_500_validation_(512, 512)](https://github.com/user-attachments/assets/e8249376-e6e4-406a-a6ad-a3bc19 …
=> Fix --input_perturbation_steps so that it actually has an effect

helpers/arguments.py
"ai-toolkit" choice was added to adapters for flux but not exposed in `--flux_lora_target` arguments. This PR fixes that
=> add `ai-toolkit` option in --flux_lora_target choices

train.py
This fixes issue #780. I tested it with a batch size of 2. I'm also fixing the schedule to what I believe is correct based on SD3-Turbo paper. Schnell training is still broken based on a quick 500 step test run. So the advice is still to stay away from Schnell.
=> Fixes for --flux_fast_schedule

toolkit/captioning/caption_with_blip3.py
caption_with_blip3.py only worked on mps devices, this commit makes it work on CUDA, too.
=> Fix caption_with_blip3.py on CUDA

helpers/training/save_hooks.py
was running into a bug where `_save_full_model` would break during multi-gpu full finetuning.
The function was being run by all processes, and 
```
for item in os.listdir(temporary_dir):
s = os.path.join(temporary_dir, item)
d = os.path.join(output_dir, item)
if os.path.isdir(s):
shutil.copytree(s, d, dirs_exist_ok=True)  # Python 3.8+
else:
shutil.copy2(s, d)
shutil.rmtree(temporary_dir)
```
would error out because the temporary_dir would get deleted while other processes were trying to copy files that no longer existed. 
Fixed by returning early if not main process.
=> fix: only run save full model on main process

train.py
```
2024-08-26 23:13:49,032 [INFO] (BaseMetadataBackend) Enforcing minimum image size of 0.0. This could take a while for very-large datasets.
2024-08-26 23:13:49,033 [WARNING] (BaseMetadataBackend) Removing bucket 0.68 due to insufficient samples; your batch size may be too large for the small quantity of data (batch_size=8 > sample_count=4).                                                                 | 0/23 [00:00<?, ?it/s]
2024-08-26 23:13:49,033 [WARNING] (BaseMetadataBackend) Removing bucket 1.46 due to insufficient samples; your batch size may be too large for the small quantity of data (batch_size=8 > sample_count=4).
2024-08-26 23:13:49,033 [WARNING] (BaseMetadataBackend) Removing bucket 0.57 due to insufficient samples; your batch size may be too large for the small quantity …
```
=> combine the vae cache clear logic with bucket rebuild logic

helpers/arguments.py, helpers/models/flux/__init__.py, helpers/training/__init__.py, train.py
GPT4o helpfully generated this chart to demonstrate the guidance schedule
=> flux: mobius-style training via augmented guidance scale

documentation/DATALOADER.md
=> fixing typo in flux document for preserve_data_backend_cache key

helpers/training/optimizer_param.py
set optimizer details to empty dict to prevent variable undefined error when using deepspeed
=> fix: set optimizer details to empty dict w/ deepspeed

train.py
wandb_logs is undefined if `accelerator.sync_gradients` is False
=> fix: make sure wandb_logs is always defined

documentation/DATALOADER.md
The docs show `instance_prompt` when the value should be `instanceprompt`.
```
2024-08-29 15:28:24,677 [ERROR] (__main__) Unsupported caption strategy: instance_prompt. Supported: 'filename', 'textfile', 'parquet', 'instanceprompt', traceback: Traceback (most recent call last):
```
=> Dataloader Docs - Correct caption strategy for instance prompt

train.sh
In https://github.com/bghira/SimpleTuner/commit/79ded80af4803a88b71b484b3cefe8f9976b6d0d the `--flux`, `--sd3`, etc arguments were remove and instead need to be passed as `--model_family=<model>`. The `train.sh` script wasn't updated so if you're freshly cloning the repo and running the script it will fail to run.
=> Update TRAINER_EXTRA_ARGS for model_family

helpers/training/trainer.py
Fix text encoders staying in system RAM after train.py was refactored in #899. This reduces system RAM usage by 9.1 GB for me while training Flux.
=> Fix text encoder nuking regression

OPTIONS.md, helpers/arguments.py, helpers/models/flux/__init__.py, helpers/training/trainer.py
This is based on discussion after PR #892. This fixes --flux_schedule_shift by applying the shift to the sigmas. This makes it equivalent with Kohya's code.
This pull request also adds new option --flux_schedule_auto_shift for resolution-dependent shifting based on official Flux inference code:
https://github.com/black-forest-labs/flux/blob/b4f689aaccd40de93429865793e84a734f4a6254/src/flux/sampling.py#L66
People on Discord have been trying this yesterday already and results have been positive. Previous version of the code is here (before rebasing it due refactored train.py):
https://github.com/mhirki/SimpleTuner/commit/7cafb8677543923d11dd00197f0f122d69920cf4
I tested the code using my previous configuration from this run:
https://huggingface.co/mikaelh/flux-sanna-marin-v0.4-fp8-adan2
One …
=> Fix Flux schedule shift and add resolution-dependent schedule shift

helpers/configuration/cmd_args.py, helpers/training/trainer.py
This PR introduces the option to disable all logging by specifying --report_to none. Previously, logs were automatically reported to supported integrations like Tensorboard, Wandb, or Comet. With this change, users can now choose to disable logging entirely if desired, enhancing flexibility in scenarios where logging is not needed.
=> Add `"none"` to --report_to argument

OPTIONS.md, configure.py, helpers/configuration/cmd_args.py, helpers/training/adapter.py
As suggested on Reddit by TheLastBen:
https://www.reddit.com/r/StableDiffusion/comments/1f523bd/good_flux_loras_can_be_less_than_45mb_128_dim/
I'm currently testing --flux_lora_target=tinier with a rank 16 LoRA and it's having some effect:
| 100 steps | 1300 steps |
| --- | --- |
| ![step_100_validation_1024x1024](https://github.com/user-attachments/assets/4c4d951e-8a09-4faa-8b48-8e294b04419d) | ![step_1300_validation_1024x1024](https://github.com/user-attachments/assets/8b5a0dd3-a7c0-49f2-afa1-b429a7353f74) |
File size is only 576 kB for this ultra-tiny LoRA. My learning rate is at 1e-3 with adamw_bf16 optimizer.
=> Add support for tiny PEFT-based Flux LoRA based on TheLastBen's post on Reddit

config/lycoris_config.json.example
This pull request replaces old non-functional lycoris_config.json.example (see issues #843 and #844) with the default configuration generated by configure.py.
=> Update lycoris_config.json.example with working defaults

configure.py, helpers/configuration/cmd_args.py, helpers/training/default_settings/safety_check.py, helpers/training/optimizer_param.py, helpers/training/optimizers/soap/__init__.py, helpers/training/quantisation/__init__.py, helpers/training/quantisation/quanto_workarounds.py, helpers/training/trainer.py
well this is a fat optim and consumes about 2x the vram as adamw would.
with int8 on 4090 it will OOM. you have to use int4, or a 48G device.
=> SOAP optimiser; int4 fixes for 4090

README.md, documentation/quickstart/FLUX.md, helpers/data_backend/aws.py, helpers/data_backend/local.py, helpers/models/flux/__init__.py, helpers/models/flux/pipeline.py, helpers/training/__init__.py, helpers/training/diffusion_model.py, helpers/training/optimizer_param.py, helpers/training/save_hooks.py, helpers/training/trainer.py, install/apple/poetry.lock, install/apple/pyproject.toml, install/rocm/poetry.lock, install/rocm/pyproject.toml, poetry.lock, pyproject.toml
Unlocks 10G GPU training for Flux LoRA / LyCORIS.
=> Bits n Bytes NF4 training

helpers/models/flux/transformer.py, helpers/training/diffusion_model.py
`apply_rope` was removed from the most recent transformers, so I stubbed it in to keep attention masking models working.
=> Fix attention masking transformer for flux

documentation/DISTRIBUTED.md, helpers/training/save_hooks.py, helpers/training/trainer.py
- disable validations / benchmarking for deepspeed zero 3, fixing #965 
- save training state for every rank and apply them correctly at resume time
=> multi-node training fixes for state tracker

documentation/DATALOADER.md, documentation/DREAMBOOTH.md, documentation/quickstart/FLUX.md, helpers/data_backend/factory.py, helpers/multiaspect/dataset.py, helpers/training/collate.py, helpers/training/default_settings/safety_check.py, helpers/training/quantisation/quanto_workarounds.py, helpers/training/trainer.py
Implements and closes #1031 
Add `is_regularisation_data=true` to your regularisation dataset.
Only functions for LyCORIS for now.
=> implement regularisation dataset parent-student loss for LyCORIS training

README.md, documentation/DATALOADER.md, documentation/DREAMBOOTH.md, documentation/quickstart/FLUX.md, helpers/data_backend/factory.py, helpers/image_manipulation/training_sample.py, helpers/multiaspect/sampler.py, helpers/training/collate.py, helpers/training/default_settings/safety_check.py, helpers/training/state_tracker.py, helpers/training/trainer.py, toolkit/datasets/masked_loss/generate_dataset_masks.py, train.py
See the DREAMBOOTH guide for more info.
=> fix controlnet training for sdxl and introduce masked loss preconditioning

helpers/data_backend/factory.py, helpers/image_manipulation/training_sample.py, helpers/multiaspect/dataset.py, helpers/training/collate.py, poetry.lock, pyproject.toml
when square cropping, it worked alright, but when aspect bucketing with random crops or random/closest bucket, the mask would not prepare the same as the origin sample.
a prepare_like method is added to prepare one sample using the same transforms as another.
optimises startup speed of larger datasets by skipping the aspect bucketing and VAE caching steps which are not necessary.
=> refactor how masks are retrieved

helpers/data_backend/factory.py
caption-dropout_probability -> caption_dropout_probability
=> fix(typo): correct arg name in warning

helpers/prompts.py
This pull request adds deduplication of captions. I ran a little benchmark comparing two deduplication methods with 9997 captions from the pseudo-camera-10k dataset.
`captions = list(dict.fromkeys(captions))`
Deduplication complete in 875493 ns.
Deduplication complete in 865751 ns.
Deduplication complete in 880586 ns.
`captions = list(set(captions))`
Deduplication complete in 1007244 ns.
Deduplication complete in 943887 ns.
Deduplication complete in 936598 ns.
So building a dictionary is the fastest method. These are nanoseconds meaning that 9997 captions were deduplicated in less than 1 millisecond.
=> Add deduplication of captions

helpers/training/default_settings/safety_check.py
As an alternative to PR #1105, just throw an error if both --flux_schedule_auto_shift and --flux_schedule_shift are enabled, forcing the user to explicitly choose one of them.
Since the default value of --flux_schedule_shift is now 3 after commit 4a7d42320e4457be7e52540cac1df191a1b88596, people need to set it 0 if they want to continue training with auto-shift.
=> Throw an error if both --flux_schedule_auto_shift and --flux_schedule_shift are enabled.

tests/test_trainer.py
My previous pull request #1106 caused the unit tests to fail. Setting both flux_schedule_shift and flux_schedule_auto_shift explicitly in the unit test seems to fix the issue.
```
======================================================================
ERROR: test_misc_init (test_trainer.TestTrainer.test_misc_init)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/unittest/mock.py", line 1378, in patched
return func(*newargs, **newkeywargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/runner/work/SimpleTuner/SimpleTuner/tests/test_trainer.py", line 154, in test_misc_init
trainer = Trainer(disable_accelerator=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
=> Fix unit test failure after PR #1106

documentation/quickstart/FLUX.md
added configuration information for pre-trained model support
=> Updating Flux Quickstart Doc with Pre-Trained Model Info

helpers/training/validation.py
I saw the random validation errors were back after commit 48cfc09db92ff64281ab7eb6ca9e41f59bb9e23f removed some of my earlier fixes for the random validation issues. This time I decided to dig to the bottom of the issue of why the pipeline is randomly on the cpu.
The root cause turned out to be an early return in `setup_pipeline` which means that this line at the end of `setup_pipeline` is never executed:
```python
self.pipeline = self.pipeline.to(self.inference_device)
```
And torch.compile before that is also never called.
I did notice that moving the entire pipeline to the accelerator device has some unwanted side-effects. It also moved text_encoder_2 and text_encoder_3 to the GPU when I was testing with SD3.5. Setting text_encoder_2 and text_encoder_3 to None in …
=> Fix random validation errors for good (and restore torch.compile for the validation pipeline at the same time)

helpers/data_backend/local.py
so that we do not read partial writes or corrupt multiprocess writes
=> local data backend should have file locking for writes and reads

configure.py, helpers/configuration/cmd_args.py, helpers/models/flux/transformer.py, helpers/training/default_settings/safety_check.py, helpers/training/diffusion_model.py, helpers/training/gradient_checkpointing_interval.py, helpers/training/trainer.py, tests/test_trainer.py
thanks to snek on discord for the heads-up to [Erwann Millon's post](https://x.com/ErwannMillon/status/1828890824337436993) on a quick win for gradient checkpointing.
while investigating i found that inference was running w/ checkpointing even though we're not calculating grads so that's been disabled before validations run too.
generation time from 29s to 14s for a 28 step img on flux dev on a 4090 with a 5800X3D and fp8-quanto 
when training with a rank 1 lora we can use `--gradient_checkpointing_interval=2` on a 24G 4090 w/ fp8-quanto and speed up from 4.25 second per training step to 3.00 second per training step at 1024px
otherwise you'd be able to train much larger LoRA on 24G.
haven't tested this on larger GPUs yet, where the benefits are greater and allows higher intervals. …
=> gradient checkpointing speed-up

configure.py
also updates default recommendations for cfg
=> configurator should avoid asking about checkpointing intervals when the model family does not support it

helpers/models/flux/transformer.py
fixes #1223 by just checking rank 0 for H100 access always.
=> flux: use rank 0 for h100 detection since that is the most realistic setup

OPTIONS.md, documentation/quickstart/FLUX.md, documentation/quickstart/SANA.md, documentation/quickstart/SD3.md, helpers/configuration/cmd_args.py, helpers/models/flux/__init__.py, helpers/models/sana/transformer.py, helpers/publishing/metadata.py, helpers/training/default_settings/safety_check.py, helpers/training/trainer.py, tests/test_model_card.py, tests/test_trainer.py
deprecated options and their replacement:
```py
deprecated_options = {
"flux_beta_schedule_alpha": "flow_beta_schedule_alpha",
"flux_beta_schedule_beta": "flow_beta_schedule_beta",
"flux_use_beta_schedule": "flow_use_beta_schedule",
"flux_use_uniform_schedule": "flow_use_uniform_schedule",
"flux_schedule_shift": "flow_schedule_shift",
"flux_schedule_auto_shift": "flow_schedule_auto_shift",
"flow_matching_sigmoid_scale": "flow_sigmoid_scale",
}
```
=> rename and deprecate flux option names

helpers/training/default_settings/safety_check.py, helpers/training/optimizer_param.py
Small modification to enable running on AMD GPUs:
1. bypass GPU mem size check if torch.cuda.version is none
2. reordered the optimizer list and added an if clause to check if bitsandbytes ademamix optimizers are available. These optimizers are not yet in the multibackend bitsandbytes for rocm.
The modified code was tested on AMD MI300X and Nvidia H100.
=> Small fixes for running on AMD GPUs

helpers/image_manipulation/training_sample.py, helpers/multiaspect/image.py
this impacts square image inputs, which slipped by initial tests since the debug image creation misses the very last step of creating a final output.
if you were using crop=false and had square images which differ from the `resolution`, this would cause problems like zoomed and cropped elements.
=> add a special case for square input images where we need to resize to the target as intermediary, which can be considered a safe operation

.github/workflows/python-tests.yaml
Makes poetry run the tests from the right folder.
=> Fixing broken python-tests action

documentation/DATALOADER.md, helpers/data_backend/factory.py, helpers/metadata/backends/base.py, helpers/metadata/backends/discovery.py, helpers/metadata/backends/parquet.py, tests/test_metadata_backend.py
=> (#1113) add minimum and maximum aspect ratio bucket parameter and associated tests

OPTIONS.md, helpers/configuration/cmd_args.py, helpers/training/trainer.py
In some cases, we want to train without doing any validation whatsoever, and without losing any time on validation (for example, in a production setting where we're going to train a bunch of loras with the same settings but with different data) or textembed caching.
At the moment, this isn't possible:
- The training loop crashes if the validation prompt library is empty AND the unconditional prompt is disabled.
- This means we always lose some time on precomputing the text embeddings for whatever placeholder validation prompt is present.
- The post training validation cannot actually be disabled at all.
This PR adds a simple option that disables the attempt to precache the validation prompts, and also blocks any intermittent or post-training validation.
=> Add an option to completely disable validation

helpers/configuration/cmd_args.py, helpers/training/trainer.py
* By default, `--lr-scale` is the product of learning rate, batch size, gradient accumulation, and number of GPUs. This adds an additional option `--lr-scale-sqrt` to instead multiply by the square root of (batch size, gradient accumulation, and number of GPUs). This is being provided as an option as there are multiple schools of thought on what is "correct" - so let the user decide.
* Related log output cleaned up a bit to display scientific notation and emit useful info at the end.
Example output:
`--lr-scale`:
```
Scaling learning rate from 1.0e-04 to 8.0e-04 due to --lr-scale (bsz: 8, ga: 1, nprocs: 1)
```
`--lr-scale` and `--lr-scale-sqrt`:
```
Scaling learning rate from 1.0e-04 to 2.8e-04 due to --lr-scale and --lr-scale-sqrt (bsz: 8, ga: 1, nprocs: 1)
```
=> Support --lr-scale-sqrt and tidy up associated output

train.sh
* HF_HOME was specified in the Dockerfile as /workspace/huggingface via commit 1584ddd27. When running `accelerate config`, this is the base path that will actually be used to write the config.
Note: HF_HOME pointing to this location by default also makes sense as it provides a suitable default path from which to map volumes which may involve pre-populated models whereas mapping volumes to /root/.cache/huggingface makes a lot less sense.
=> train.sh: Respect HF_HOME

docker-start.sh, documentation/DOCKER.md
docker-start.sh:
* HUGGING_FACE_HUB_TOKEN is deprecated and HF_TOKEN should be used. WANDB_TOKEN likely never existed and WANDB_API_KEY is correct. Since people may have these env-vars set in various places, respect them as a fallback choice if the non-deprecated/correct version isn't in use, but prefer the latter.
DOCKER.md:
* Clean up documentation to use the right env-var names.
Notes:
HF: https://huggingface.co/docs/huggingface_hub/package_reference/environment_variables#deprecated-environment-variables
WANDB: https://docs.wandb.ai/guides/track/environment-variables/
=> Use correct HF token and WanDB api-key env-vars

helpers/models/hidream/model.py
`img_sizes` and `img_ids` need to be repeated based on batch size. In the original reference code, this was conditional behind `if self.do_classifier_free_guidance:` which I originally removed without too much thought:
https://github.com/HiDream-ai/HiDream-I1/blob/6629d04d71c5f344298128dd69af42505d0745a0/hi_diffusers/pipelines/hidream_image/pipeline_hidream_image.py#L629
Turns out, we do need this code but repeating `B` times instead of `2 * B` times is enough for training.
Just for reference, this is the error that was thrown before this fix with train_batch_size = 4:
```
Traceback (most recent call last):
File "/nvme/home/mikaelh/Stable_Diffusion/bghira/SimpleTuner.blackwell/train.py", line 71, in <module>
trainer.train()
File "/nvme/home/mikaelh/Stable_Diffusion/bghira/SimpleTuner.black …
```
=> Fix HiDream training for train_batch_size > 1

helpers/models/common.py, helpers/training/trainer.py
I tried parent-student training with HiDream but I never saw step_loss dropping to almost zero which indicated that parent-student training was broken.
Commit 6ac8ca727cac36aa9bba728c9ca44ab90135934a didn't quite fix parent-student training because prepared_batch["target"] is not used everywhere.
I added a check for prepared_batch["target"] to `get_prediction_target` in helpers/models/common.py. I also changed the contents of prepared_batch["target"] so that it's a `torch.Tensor` instead of a `dict`.
After the fix, I can see the loss sometimes dropping to almost zero as expected:
```
Epoch 1/1, Steps:   2%|▎                | 100/6000 [14:40<13:03:08,  7.96s/it, grad_absmax=0.0645, lr=0.0001, step_loss=3.24]
Epoch 1/1, Steps:   2%|▏            | 101/6000 [16:37<66:36:32, 40.65s/it, …
```
=> Fix parent-student training broken by v2 refactor

helpers/data_backend/factory.py, helpers/metadata/backends/base.py
configure_multi_databackend/split_buckets_between_processes:
* If max_train_steps is false, padding should be used with accelerator.split_between_processes otherwise a bucket with an odd number of images, an odd effective_batch_size, or the count of trimmed_images otherwise ending up as odd results in each process potentially having a different idea of max_train_steps after _recalculate_training_steps() is called (as it takes into account metadata bucket counts). In the case where the main process thinks its max_train_steps is greater than any other non-main processes when train() arrives at that step, it will hang until timeout on self.accelerate.gather() as a non-main process has left the training loop but the main process still has steps outstanding.
An alternative way of solving this …
=> split_buckets_between_processes: Fix issue with imbalanced steps between processes

helpers/models/ltxvideo/model.py
also removed invalid v0.9.1 flavour.
=> ltxvideo tokeniser shoudl use AutoTokenizer to avoid class mismatches

helpers/models/hidream/pipeline.py
Hi, we are HiDream.ai official team. Recently, we updated the scheduler configuration in our Hugging Face model repositories to make it easier to run inference directly with Diffusers. However, we understand that this change may have caused inconvenience for some users.
To ensure compatibility, we recommend updating the pipeline code as follows:
```python
elif isinstance(self.scheduler, UniPCMultistepScheduler):
self.scheduler.set_timesteps(num_inference_steps, device=device)  # , shift=math.exp(mu))
timesteps = self.scheduler.timesteps
```
This way, inference will work properly regardless of whether the user is using `FlowUniPCMultistepScheduler` from our GitHub repository or `UniPCMultistepScheduler` from Diffusers.
> [!NOTE]
> this scheduler update does not change the actual behavior …
=> Added check for UniPCMultistepScheduler

helpers/models/hidream/transformer.py
Just repeating commit 614eef438023132b90e53c98e93388110bcad488 and renaming FeedForwardSwiGLU to FeedForward. FeedForward training was fixed in commit e96bdd8bfcf070c55f39b87e55d94c1935379aae after that.
I tested resuming from a checkpoint after adjusting my lycoris config to match and the training is running just fine.
=> Rename FeedForwardSwiGLU back to FeedForward for convenience

helpers/caching/vae.py, helpers/models/common.py
https://discord.com/channels/696818921625485342/1252663652583084123/1363334445460881570
```
An error occurred in a future: Input video must be a numpy array or a list of frames., file <frame at 0x55942965dbb0, file 'SimpleTuner/helpers/caching/vae.py', line 1053, code _process_futures>, 1049, future traceback Traceback (most recent call last):
File "SimpleTuner/helpers/caching/vae.py", line 1049, in _process_futures
future.result()
File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
return self.__get_result()
File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
raise self._exception
File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File …
```
=> When running sample transforms, the dataset_type should be considered so that we do not run video transforms on image

helpers/data_backend/factory.py
```
Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)
Traceback (most recent call last):
File "/mnt/Linux/Code/SimpleTuner/train.py", line 50, in <module>
trainer.init_data_backend()
File "/mnt/Linux/Code/SimpleTuner/helpers/training/trainer.py", line 500, in init_data_backend
raise e
File "/mnt/Linux/Code/SimpleTuner/helpers/training/trainer.py", line 473, in init_data_backend
configure_multi_databackend(
File "/mnt/Linux/Code/SimpleTuner/helpers/data_backend/factory.py", line 1224, in configure_multi_databackend
init_backend["text_embed_cache"].compute_embeddings_for_prompts(
File "/mnt/Linux/Code/SimpleTuner/helpers/caching/text_embeds.py", line 294, in …
```
=> when encoding text embeds,  force the move to accelerator on round one

helpers/configuration/cmd_args.py, helpers/training/trainer.py
* --checkpointing_rolling_steps: Support creating "rolling" checkpoint saves that are independently tracked from normal checkpoint saves and which use a total limit of 1. This allows saving checkpoints more frequently in environments where spontaneous interruption is common (e.g. spot instances) but without requiring the config to specify an overly aggressive value for --checkpointing_steps.
* --checkpointing_use_tempdir: Write out all checkpoint saves to checkpoint-STEP-tmp and then atomically rename to checkpoint-STEP after success. This ensures that partially written state is never used for resuming as it's almost impossible to recover from and requires manual deletion which is a problem for automated resumes.
* init_resume_checkpoint: Move "latest" checkpoint code into …
=> Add support for --checkpointing_rolling_steps and --checkpointing_use_tempdir

helpers/data_backend/factory.py, helpers/training/trainer.py
* configure_multi_databackend: add missing is_local_main guard
* init_clear_backend_cache: add missing is_local_main guard
Both of these were contributing to multiple processes racing each other to delete the same cache files resulting in different processes having different ideas of reality depending on who won.
=> Fix missing barriers contributing to multi-process cache races

simpletuner/helpers/webhooks/handler.py
Fix an error where sending structured data through the webhook fails due to unserializable objects.
This fix simply replaces dictionary values that are not JSON-serializable from `data`. A more explicit way might be to sanitize input to `_send_webhook_raw(...)` beforehand.
The error occurs in simpletuner/helpers/training/trainer.py, as the `Trainer.state` dictionary includes unserializable objects, such as a `ProjectConfiguration` instance.
```python
[...]
if (
self.config.webhook_reporting_interval is not None
and self.state["global_step"]
% self.config.webhook_reporting_interval
== 0
):
structured_data = {
"state": self.state,
"loss": round(self.train_loss, 4),
"parent_loss": parent_loss,
"learning_rate": self.lr,
"epoch": epoch,
"final_epoch": self.config.num_train_epochs,
} …
```
=> fix: raw webhook send error

simpletuner/helpers/configuration/loader.py
`parser.parse_args(...)` in simpletuner/helpers/configuration/cmd_args.py expects a list of strings instead of a dictionary object
Steps to reproduce error:
```python
from simpletuner.helpers.training.trainer import Trainer
trainer = Trainer(
config={'model_family': 'sdxl', 'model_type': 'lora', 'optimizer': 'optimi-adamw'},
exit_on_error=True,
)
```
```
[ERROR] Could not parse input: {'model_family': 'sdxl', 'model_type': 'lora', 'optimizer': 'optimi-adamw'}
[ERROR] Traceback (most recent call last):
File "/Users/redevined/Projects/SimpleTuner/simpletuner/helpers/configuration/cmd_args.py", line 2401, in parse_cmdline_args
args = parser.parse_args(input_args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/redevined/.pyenv/versions/3.11.11/lib/python3.11/argparse.py", line 1874, in parse_args …
```
=> fix: type error when passing argument dict to Trainer initialization
