README.md, helpers/dreambooth_dataset.py, helpers/sdxl_embeds.py, helpers/vae_cache.py, inference.py, inference_snr_test.py, interrogate.py, sdxl-env.sh.example, train_sdxl.py, train_sdxl.sh
vae caching concat fix
skip cache update (for now)
logging improvements
missing script additions/updates
=> follow-up fixes

helpers/aspect_bucket.py, helpers/dreambooth_dataset.py, helpers/sdxl_embeds.py, train_sdxl.py
* multiprocess aspect bucketing - _**tres**_ faster!!!
* progress bar for text embed processing
=> Aspect bucketing optimizations

helpers/aspect_bucket.py, train_sdxl.py
With this, a 6-image dataset can successfully train.
=> Fixes for some small-dataset training issues

train_sd21.py
=> SD 2.x: fix the final push_to_hub call, so that it creates the repo before pushing to repo_id

README.md, helpers/arguments.py, train_sd21.py, train_sdxl.py
=> MultiGPU / random seed fix | Learning rate schedule calculation fix for gradient accumulation steps

train_sdxl.py
=> (#91) fix weights & biases tracker project name / run name (with @zhuliyi0)

helpers/caching/vae.py
Reverts bghira/SimpleTuner#124
=> Revert "Feature/vae batch encode"

train_sd21.py
=> SD 2.x: Add --track_luminance option for tracking luminance, do not track by default due to computational overhead

helpers/arguments.py, helpers/legacy/validation.py, train_sd21.py, train_sdxl.py
=> Add --validation_noise_scheduler flag for switching to Euler/UniPC/Euler A for validations

helpers/arguments.py, helpers/legacy/validation.py, train_sd21.py, train_sdxl.py
=> Add --validation_num_inference_steps to set the number of inference steps for different schedulers

helpers/legacy/validation.py, train_sd21.py
=> (#153) missing import in validations module when user_prompt_library is in use

helpers/arguments.py, helpers/training/custom_schedule.py
=> Follow-up: improve naming of parameters for timestep bias, and an ability to bias a specific range within the middle

helpers/multiaspect/sampler.py
=> Simply do not pre-process the image or check for aspect bucket correctness, as those issues have been solved

train_sd21.py, train_sdxl.py
=> resolve reference to bool as callable when determining whether we track luminance values

helpers/arguments.py, helpers/caching/sdxl_embeds.py, helpers/legacy/validation.py, helpers/prompts.py, train_sdxl.py
=> Compel for long prompt handling, opt-out via --disable_compel

helpers/data_backend/factory.py, helpers/multiaspect/bucket.py, helpers/multiaspect/image.py, toolkit/captioning/caption_with_cogvlm.py, toolkit/captioning/caption_with_llava.py
when loading a config with a crop = False for a single dataset while starting with `--crop=true` cmdline arg, it will crop all images.
=> multidatabackend fix for non-square image training, data bucket config override

helpers/caching/sdxl_embeds.py
=> text embedding cache should stop writing and kill the thread when we finish

README.md, documentation/CONTROLNET.md, helpers/arguments.py, helpers/caching/vae.py, helpers/data_backend/factory.py, helpers/image_manipulation/training_sample.py, helpers/legacy/metadata.py, helpers/legacy/sd_files.py, helpers/legacy/validation.py, helpers/metadata/backends/json.py, helpers/metadata/backends/parquet.py, helpers/multiaspect/dataset.py, helpers/multiaspect/sampler.py, helpers/sdxl/save_hooks.py, helpers/training/collate.py, helpers/training/state_tracker.py, helpers/training/validation.py, sd21-env.sh.example, sdxl-env.sh.example, tests/test_collate.py, tests/test_dataset.py, toolkit/datasets/controlnet/create_canny_edge.py, train_sd21.py, train_sd2x.sh, train_sdxl.py, train_sdxl.sh
example dataset:
```json
[
{
"id": "antelope-data",
"conditioning_data": "antelope-conditioning",
"type": "local",
"dataset_type": "image",
"instance_data_dir": "/Volumes/ml/datasets/canny-edge/animals/antelope-data",
"caption_strategy": "instanceprompt",
"instance_prompt": "an antelope",
"metadata_backend": "json",
"minimum_image_size": 1.0,
"maximum_image_size": 1.0,
"target_downsample_size": 1.0,
"disable": false,
"cache_dir_vae": "/Volumes/ml/cache/vae/sdxl/antelope-data",
"probability": 1.0,
"scan_for_errors": true,
"skip_file_discovery": "",
"preserve_data_backend_cache": false,
"vae_cache_clear_each_epoch": false,
"repeats": 1,
"crop": true,
"crop_aspect": "square",
"crop_style": "center",
"resolution": 1.0,
"resolution_type": "area",
"cache_file_suffix": "controlnet-sdxl"
},
{ …
```
=> controlnet training support (sdxl+sd2x)

helpers/caching/vae.py, helpers/image_manipulation/training_sample.py
…l way to ease the pain of implementation
=> randomised bucketing should correct the intermediary size in a special way to ease the pain of implementation

inference_comparison.py
Hi @bghira, great library!
I thought this would be proper.
=> Unload LoRA weights before deleting pipeline object

train_sd2x.sh, train_sdxl.sh
I'll expect my payment in spanish bullion
=> Super important pull request to fix literally unusable problem

helpers/arguments.py, helpers/caching/memory.py, train_sd21.py, train_sdxl.py
This is a preliminary PR for [#481](https://github.com/bghira/SimpleTuner/issues/481)
With the `garbage_collection` function, I checked a lot of repos, and this looks like the most common sequence.
I want to dedupe the `garbage_collection` function from the `train_*` scripts, but I don't have the intuition to put it into the correct spot. Can you help here @bghira? 
Thanks!
=> Added CUDA GC every x steps

helpers/sdxl/save_hooks.py, train_sdxl.py
I took the liberty to refactor the LoRA related bits in the hooks but LMK if you would like me to discard that. 
Additionally, it might be nice to configure some formatting and linting on the repository. Do you have recommendations? I use this: https://gist.github.com/sayakpaul/a48a0f63d0e346164a97c687f27c5b51.
=> Support Hunyuan DiT loading

helpers/caching/vae.py, helpers/data_backend/local.py, helpers/metadata/backends/base.py, helpers/multiaspect/sampler.py, toolkit/datasets/retrieve_s3_bucket.py, train_sdxl.py
It's not clear why some configurations cause this, but it's tested to work on local and aws training:
```
2024-06-30 17:18:32,819 [DEBUG] (MultiAspectSampler-text-1mp) (Rank: 0)  From 3 buckets, selected 1.0 (1.0) -> 528 available images, and our accumulator has 0 images ready for yielding.
2024-06-30 17:19:58,529 [DEBUG] (MultiAspectSampler-text-1mp) (Rank: 0)  From 3 buckets, selected 1.0 (1.0) -> 504 available images, and our accumulator has 0 images ready for yielding.
2024-06-30 17:21:36,244 [DEBUG] (MultiAspectSampler-text-1mp) (Rank: 0)  From 3 buckets, selected 1.0 (1.0) -> 480 available images, and our accumulator has 0 images ready for yielding.
2024-06-30 17:24:33,791 [DEBUG] (MultiAspectSampler-text-1mp) (Rank: 0)  From 3 buckets, selected 1.0 (1.0) -> 456 available images, …
```
=> Fix bucket search for unseen images not containing the absolute path to the image

README.md, config/config.env.example, documentation/QUICKSTART.md, documentation/quickstart/KOLORS.md, helpers/arguments.py, helpers/caching/text_embeds.py, helpers/kolors/pipeline.py, helpers/training/collate.py, helpers/training/state_tracker.py, helpers/training/validation.py, train.py, train.sh
We're going to add Kolors to its own feature branch, and this issue encompasses the plan to integrate this model.
If you wish to take one of the components, simply comment here and open a pull request to this branch (`feature/kolors`). Please do not open your pull request to the main branch.
=> [wip] kolors

README.md, TUTORIAL.md, config/config.env.example, documentation/DREAMBOOTH.md, documentation/quickstart/FLUX.md, documentation/quickstart/KOLORS.md, documentation/quickstart/SD3.md, helpers/arguments.py, helpers/caching/text_embeds.py, helpers/training/__init__.py, helpers/training/custom_schedule.py, helpers/training/quantisation/__init__.py, install/apple/poetry.lock, install/apple/pyproject.toml, train.py
it does not yet work with saving or loading the loras. or is it just an MPS issue, who knows.
also you can't resume training a lora and enable quanto on the base model. it will complain.
=> quanto: exploring low-precision training.

helpers/training/save_hooks.py, tests/test_save_hooks.py
Adds basic save hook manager tests to ensure we have desired attributes correctly set. 
@bghira if this looks good to you, I will add it for other models and have it ready for review.
=> [Tests] basic save hook tests

OPTIONS.md, config/config.env.example, configure.py, documentation/MIXTURE_OF_EXPERTS.md, documentation/quickstart/FLUX.md, helpers/arguments.py, helpers/data_backend/base.py, helpers/data_backend/factory.py, helpers/metadata/backends/base.py, helpers/metadata/backends/json.py, helpers/metadata/backends/parquet.py, helpers/multiaspect/sampler.py, helpers/training/adapter.py, helpers/training/optimizer_param.py, tests/test_metadata_backend.py, train.py, train.sh
Follow up of #739. This PR bundles the optimizer-related things (more specifically, optimizer params and the params it's supposed to optimize) into a module.
=> Follow up from #739

helpers/arguments.py, helpers/training/adapter.py, train.py
Initialize Flux lora from file.
- unets are not tested yet. Maybe the prefix name has to change
- dora not tested yet
- I removed the get_peft_model line. Can you double check on your side why this line was in there in first place? For me loras don't work if you have both, get_peft_model AND add_adapter (there is also a warning from peft saying that lora adapters are created twice)
=> Lora init from file

helpers/arguments.py, helpers/training/adapter.py
Add context+ffs as additional option. I also proposed a change in the documentation of the argument, but revert that if you like.
=> add new lora option for context+ffs

helpers/arguments.py, helpers/models/flux/transformer.py, helpers/training/diffusion_model.py, helpers/training/save_hooks.py, tests/test_save_hooks.py, train.py
- Fixes bugs in the Transformer2D class for flux
- Adds attention masking and the new FluxTransformer2DModelWithMasking model
=> Add attention masking to the custom helpers/flux/transformer.py

train.py
the checkpoints were saving without converting the transformer safetensor keys and after confirming with Sayak, this is the correct way to export the pipeline for transformers as well.
=> state dict export for final pipeline

helpers/training/quantisation/__init__.py
…ng ago now; add warning about int4
=> quanto: remove warnings about int8/fp8 confusion as it happened so long ago now; add warning about int4

helpers/training/trainer.py
the init_lora argument now support a lokr checkpoint
=> added lokr lycoris init_lora

OPTIONS.md, documentation/quickstart/FLUX.md, helpers/configuration/cmd_args.py, helpers/training/default_settings/safety_check.py, helpers/training/quantisation/__init__.py, helpers/training/quantisation/quanto_workarounds.py
an experiment to test the impact of activation quantising on a 4090:
=> quanto: activations sledgehammer

configure.py, helpers/prompt_expander/__init__.py
when running configure.py, if no user prompt library exists, a crappy one will be generated by default.
if you have a user prompt library already, it will not alter it.
=> add prompt expander based on 1B Llama model

helpers/caching/vae.py, helpers/training/trainer.py
fixes #977 by correctly placing vae cache entries inside subdirs
=> fix vae cache dir creation for subdirs

helpers/caching/vae.py, helpers/training/trainer.py, toolkit/datasets/random_recrop_for_json_image_metadata.py
if your images were in subdirs, their cache will _probably_ be regenerated..
=> fix for nested image subdirs w/ duplicated filenames across subdirs

documentation/quickstart/SD3.md, helpers/configuration/cmd_args.py, helpers/models/omnigen/pipeline.py, helpers/models/sd3/pipeline.py, helpers/models/sd3/transformer.py, helpers/training/adapter.py, helpers/training/diffusion_model.py, helpers/training/save_hooks.py, helpers/training/validation.py, tests/test_trainer.py
Set --validation_guidance_skip_layers=[7,8,9]
=> sd3: add skip layer guidance

helpers/configuration/cmd_args.py, helpers/training/trainer.py, train.py
different method of gradient clipping where we clip instead of scale.
=> add --grad_clip_method to allow different forms of max_grad_norm clipping

helpers/configuration/cmd_args.py
updates the complex human instruction to be less shitty
=> sana: remove censorship from text inputs, improve accuracy of generated embeds and eliminate refusals

configure.py
- only Flux by default will have multi-res training enabled. every other model should use manual progressive training config updates, since progressive training is not yet supported in simpletuner in an automated manner.
- offer multi-resolution config via comma-separated values with Flux by default using multiple base resolutions and every other model defaulting to 1024px
- updated phrasing on the `repeats` parameter question to clarify that 0 is a single pass and 1 is two passes
- added `write_batch_size` to default text embed backend config to demystify this parameters' value and location
- use **absolute paths** to everything by default instead of relative paths
- enables easier use of nested subdir in datasets, since this does not error out
- the location of the caches will by …
=> updates for configure.py multi-resolution suggestions & dataset cache path handling

helpers/training/custom_schedule.py
fix #1137 by running the parent class init method
=> sine schedule needs to init the optimiser states

helpers/training/validation.py
=> fix check for running the final validations

helpers/training/optimizer_param.py, helpers/training/trainer.py
treats Prodigy like a normal optimiser so that it can have an LR scheduler applied.
=> prodigy may work best with cosine scheduler over long training runs

helpers/training/trainer.py
=> fix SDXL time ids

OPTIONS.md, helpers/configuration/cmd_args.py, helpers/models/__init__.py, helpers/training/diffusion_model.py, helpers/training/optimizer_param.py, helpers/training/schedulers.py, helpers/training/text_encoding.py, helpers/training/trainer.py
Just use a full path to a `.safetensors` file and it should work.
=> experimental: add single-file loading support for sdxl, flux, sd3

helpers/training/collate.py
fixes the error with pinning memory
=> nvidia training fix for ltxvideo (oops, tested on apple only before)

helpers/configuration/cmd_args.py, helpers/training/trainer.py, tests/test_trainer.py
Fixes the defaults parsed in #1347
=> Fix parsing of example lycoris config

helpers/training/trainer.py
Not sure whether this is the 'correct fix', but it 'works for me'. ([upstream issue](https://github.com/LoganBooker/prodigy-plus-schedule-free/issues/19))
=> resume fix for prodigy optim on new HF Accelerate

README.md, configure.py, documentation/quickstart/AURAFLOW.md, helpers/models/all.py, helpers/models/auraflow/model.py, helpers/models/auraflow/pipeline.py, helpers/models/auraflow/transformer.py, helpers/models/common.py, helpers/models/hidream/model.py, helpers/models/sd3/model.py, helpers/models/sd3/pipeline.py, helpers/training/trainer.py, helpers/training/validation.py
Reintroduces Auraflow training support.
=> Auraflow training support

helpers/models/flux/model.py
seems this was missed during the refactor.
=> (#1393) enable flux_lora_target for v2 lora loading code in flux

helpers/models/common.py, helpers/models/pixart/model.py
- pixart: use correct tokenizer loader
- fix use of transformer and unet subfolder options
=> fix unet/transformer subfolder options

install/apple/poetry.toml, install/rocm/poetry.lock, install/rocm/poetry.toml, install/rocm/pyproject.toml, poetry.toml
=> poetry: disable virtualenvs creation in local config

helpers/models/common.py
I had a hunch input perturbation would be broken after v2 refactor and I was right. While looking at the code, I also saw that offset noise was broken and fixed that too. I rearranged the code a bit because I think it makes more sense to apply offset noise first to the noise.
I tested both fixes with SDXL. Offset noise made colors more vibrant as expected and input perturbation made them even more vibrant.
=> Fix input perturbation and noise offset broken by v2 refactor

documentation/quickstart/HIDREAM.md
I updated the HiDream documentation with latest findings so they are available to more people outside Discord.
I also tried to make the config.json settings more reasonable. In particular, dropping `vae_cache_ondemand` should reduce VRAM consumption during training.
I added `use_scalar` to the lycoris config because it makes a big difference. Changing `linear_dim` to 16384 is just a small trick to avoid loss of precision when the lycoris code multiplies the weights with this value.
=> Update HiDream documentation with latest findings and better settings

helpers/configuration/cmd_args.py, helpers/data_backend/factory.py
saves time on big GPUs w/ HiDream etc.
=> disable offload at startup by default, allow opt-in via --offload_during_startup

poetry.lock, pyproject.toml
Regression was introduced in #1428
=> Reintroduce JPEG XL option and fix regression

helpers/training/state_tracker.py
* delete_cache_files, _load_from_disk, _save_to_disk: Use fnctl to take an advisory lock when reading or writing cache files. There are multiple avenues in calling code which can stomp all over cached state when run concurrently. While this locking is not perfect, it's a helpful guard to catch bad behavior.
Note: the addition of LOCK_NB + try/except can be added during troubleshooting as a useful check to detect where callers may be attempting a concurrent write (when they shouldn't be).
=> Use advisory locking while accessing cached state

helpers/image_manipulation/cropping.py, helpers/image_manipulation/training_sample.py, helpers/metadata/backends/discovery.py
face cropping should work for video now, too.
=> fix video cropping

helpers/models/common.py, helpers/models/deepfloyd/model.py, helpers/training/validation.py
clarifies code for deepfloyd/HiDream E1.
=> fixes for validations w/ static edge length models

configure.py
=> configure script should create a generic default resolution config

helpers/training/validation.py
=> evaluator should set_timesteps with mu when auto shift is enabled and scheduler supports mu

helpers/multiaspect/sampler.py
=> fix mask path handling when obj storage is in use, which does not have instance data dir

helpers/models/flux/pipeline.py
makes kontext validations look better, but doesn't make the model work any better.
=> add missing vae scale for flux vae

helpers/models/common.py, helpers/models/flux/attention.py, helpers/models/flux/model.py, helpers/models/flux/transformer.py
=> fuse/unfuse qkv projections on save/load

helpers/models/common.py, helpers/training/collate.py
Reverts bghira/SimpleTuner#1540
=> Revert "Fix accelerator and segmentation"

notebook.ipynb
it now works as the command line trainer does.
=> Update Jupyter notebook
